function u(d){var k=0;return function(){return k<d.length?{done:!1,value:d[k++]}:{done:!0}}}function z(d){var k="undefined"!=typeof Symbol&&Symbol.iterator&&d[Symbol.iterator];return k?k.call(d):{next:u(d)}}var D="function"==typeof Object.create?Object.create:function(d){function k(){}k.prototype=d;return new k},E="function"==typeof Object.defineProperties?Object.defineProperty:function(d,k,n){if(d==Array.prototype||d==Object.prototype)return d;d[k]=n.value;return d};
function F(d){d=["object"==typeof globalThis&&globalThis,d,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var k=0;k<d.length;++k){var n=d[k];if(n&&n.Math==Math)return n}throw Error("Cannot find global object");}var G=F(this);function J(d,k){if(k)a:{var n=G;d=d.split(".");for(var p=0;p<d.length-1;p++){var w=d[p];if(!(w in n))break a;n=n[w]}d=d[d.length-1];p=n[d];k=k(p);k!=p&&null!=k&&E(n,d,{configurable:!0,writable:!0,value:k})}}var K;
if("function"==typeof Object.setPrototypeOf)K=Object.setPrototypeOf;else{var L;a:{var M={R:!0},N={};try{N.__proto__=M;L=N.R;break a}catch(d){}L=!1}K=L?function(d,k){d.__proto__=k;if(d.__proto__!==k)throw new TypeError(d+" is not extensible");return d}:null}var P=K;
function Q(d,k){d.prototype=D(k.prototype);d.prototype.constructor=d;if(P)P(d,k);else for(var n in k)if("prototype"!=n)if(Object.defineProperties){var p=Object.getOwnPropertyDescriptor(k,n);p&&Object.defineProperty(d,n,p)}else d[n]=k[n];d.V=k.prototype}
J("Symbol",function(d){function k(w){if(this instanceof k)throw new TypeError("Symbol is not a constructor");return new n("jscomp_symbol_"+(w||"")+"_"+p++,w)}function n(w,x){this.a=w;E(this,"description",{configurable:!0,writable:!0,value:x})}if(d)return d;n.prototype.toString=function(){return this.a};var p=0;return k});
J("Symbol.iterator",function(d){if(d)return d;d=Symbol("Symbol.iterator");for(var k="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),n=0;n<k.length;n++){var p=G[k[n]];"function"===typeof p&&"function"!=typeof p.prototype[d]&&E(p.prototype,d,{configurable:!0,writable:!0,value:function(){return R(u(this))}})}return d});function R(d){d={next:d};d[Symbol.iterator]=function(){return this};return d}
function S(d,k){d instanceof String&&(d+="");var n=0,p=!1,w={next:function(){if(!p&&n<d.length){var x=n++;return{value:k(x,d[x]),done:!1}}p=!0;return{done:!0,value:void 0}}};w[Symbol.iterator]=function(){return w};return w}J("Array.prototype.keys",function(d){return d?d:function(){return S(this,function(k){return k})}});J("Array.prototype.entries",function(d){return d?d:function(){return S(this,function(k,n){return[k,n]})}});
(function(){function d(a){this.j={};var b=this;b.f=a;b.m=Array.a(24,function(){return q.random({o:!0,h:!0,l:.15<Math.random()})});var c=document.querySelector("#user-created-creation-template").innerHTML;b.b=b.m.map(function(h){var f=document.createElement("div");f.innerHTML=c;f=f.firstElementChild;C(f.querySelectorAll(".content"));f.querySelector(".do-edit").addEventListener("click",function(m){m.stopPropagation();m=new Event("select");m.c=h;b.a(m)});return f});a=z(b.b);for(var e=a.next();!e.done;e=
a.next())b.f.querySelector(".user-created").appendChild(e.value);a={};e=z(b.b.entries());for(var g=e.next();!g.done;a={K:a.K,L:a.L},g=e.next())g=z(g.value),a.K=g.next().value,a.L=g.next().value,setTimeout(function(h){return function(){return b.C(b.m[h.K],h.L)}}(a),20*a.K);if(!window.EventSource)return b;b.v.addEventListener("listeners",function(h){b.T(parseInt(h.data,10))});b.v.addEventListener("creation",function(h){h=new q(JSON.parse(h.data));b.C(h,
b.b.M())});return b}function k(){var a=n.call(this,".twitter-share-button")||this;a.c=null;a.loaded=!1;return a}function n(a){function b(){var e=document.querySelectorAll(a);e?(c.b=e,c.load()):setTimeout(function(){return b()},10)}this.j={};var c=this;c.b=[];b();return c}function p(a){this.j={};var b=this;b.b=a;b.c=null;a={};for(var c=z(b.b),e=c.next();!e.done;a={F:a.F},e=c.next())a.F=e.value,a.F.addEventListener("load",function(g){return function(){return g.F.update(b.c)}}(a)),a.F.addEventListener("share",
function(g){return function(){var h=new Event("share");h.U=g.F.name;h.c=b.c;b.a(h)}}(a));return b}function w(a){this.j={};var b=this;b.f=a;setTimeout(function(){return b.b(96)},1);return b}function x(a){this.j={};this.f=a;this.m();return this}function A(a){this.j={};var b=this;b.f=a;b.c=new q({});b.addEventListener("change:creation",function(){return b.v()});b.C();return b}function q(a){if("string"===typeof a)this.a(a);else if(a instanceof q)this.o=a.o,this.h=a.h,this.l=a.l;else if("object"==typeof a){var b=
function(c,e){return c instanceof l?c:c?new l({g:c,use:e}):l.a};this.o=b(a.mouth,"mouth");this.h=b(a.eyes,"eyes");this.l=b(a.ears,"ears")}}function l(a){this.use=a.use;this.g=Array.isArray(a.g)?a.g:[a.g]}function y(){this.j={}}function C(a){var b={};a=z(a);for(var c=a.next();!c.done;b={I:b.I},c=a.next())b.I=c.value,b.I.addEventListener("click",function(e){return function(g){var h=e.I.getAttribute("data-clipboard-text"),f=document.createElement("textarea");f.value=h;document.body.appendChild(f);if(navigator.userAgent.match(/ipad|iphone/i)){var m=
document.createRange();m.selectNodeContents(f);var v=window.getSelection();v.removeAllRanges();v.addRange(m);f.setSelectionRange(0,999999)}else f.select();document.execCommand("copy");document.body.removeChild(f);var t=document.createElement("div");t.classList.add("clipboard-animation");t.classList.add("icon");t.classList.add("icon-black-copy");t.style.left=window.scrollX+g.clientX+"px";t.style.top=window.scrollY+g.clientY+"px";document.querySelector("body").appendChild(t);setTimeout(function(){t.parentNode.removeChild(t)},
1500);window._paq.push(["trackEvent","Copy",h])}}(b))}y.prototype.addEventListener=function(a,b){a in this.j||(this.j[a]=[]);this.j[a].push(b)};y.prototype.a=function(a){if(!(a.type in this.j))return!0;for(var b=this.j[a.type].slice(),c=0,e=b.length;c<e;c++)b[c].call(this,a);return!a.defaultPrevented};Element.prototype.toggleAttribute||(Element.prototype.toggleAttribute=function(a,b){void 0!==b&&(b=!!b);if(null!==this.getAttribute(a)){if(b)return!0;this.removeAttribute(a);return!1}if(!1===b)return!1;
this.setAttribute(a,"");return!0});Array.a=function(a,b){for(var c=[],e=0;e<a;e++)c.push(b.call(void 0,e,c));return c};Array.prototype.M=function(){return this[this.length*Math.random()|0]};Array.prototype.B=function(a){var b=b||function(c,e){return c===e};return this.length===a.length&&this.every(function(c,e){return b.call(void 0,c,a[e])})};Array.prototype.P=function(a){return 1<a?this.concat(this.P(a-1)):this};l.prototype.toString=function(){return this.use?this.g.P(l.m[this.use]-this.g.length+
1).join(" "):""};l.prototype.s=function(a){return this.g[(a|0)%this.g.length]};l.prototype.B=function(a){return this.use===a.use&&this.g.B(a.g)};l.v=function(a){l.j=Object.keys(a).reduce(function(b,c){b[c]=a[c].map(function(e){return new l({g:e,use:c})});return b},{})};l.H=function(){return Object.keys(l.m)};l.C=function(){return l.H().reduce(function(a,b){return l.b(b).length*a},1)};l.b=function(a){return l.j[a]};l.j={};l.m={mouth:1,eyes:2,ears:2};l.a=new l({g:[""],use:null});q.prototype.B=function(a){return this.o.B(a.o)&&
this.h.B(a.h)&&this.l.B(a.l)};q.prototype.toString=function(){return this.l.s(0)+this.h.s(0)+this.o.s()+this.h.s(1)+this.l.s(1)};q.prototype.toJSON=function(){return{o:this.o.g,h:this.h.g,l:this.h.g}};q.prototype.N=function(){var a="009688 00bcd4 03a9f4 2196f3 3f51b5 4caf50 607d8b 673ab7 795548 8bc34a 8bc34a 9c27b0 cddc39 e91e63 f44336 ff5722 ff9800 ffc107".split(" ");return a[Array.prototype.reduce.call(this+"",function(b,c){return b^c.charCodeAt(0)},0)%a.length]};q.prototype.O=function(){return btoa([["mouth",
this.o],["eyes",this.h],["ears",this.l]].map(function(a){var b=z(a);a=b.next().value;b=b.next().value;return a+"~"+b.g.map(function(c){return Array.prototype.map.call(c,function(e){return e.charCodeAt(0).toString(36)}).join(".")}).join("-")}).join("_"))};q.prototype.a=function(a){a=z(atob(a).split("_"));for(var b=a.next();!b.done;b=a.next()){var c=b.value.split("~");b=c[0];""===c[1]?this.set(b,l.a):(c=c[1].split("-").map(function(e){return e.split(".").reduce(function(g,h){return g+String.fromCharCode(parseInt(h,
36))},"")}),this.set(b,new l({use:b,g:c})))}};q.prototype.get=function(a){switch(a){case "mouth":return this.o;case "eyes":return this.h;case "ears":return this.l}};q.prototype.set=function(a,b){switch(a){case "mouth":this.o=b;break;case "eyes":this.h=b;break;case "ears":this.l=b}};q.random=function(a){function b(e){return l.b(e).M()}(a=void 0===a?null:a)||(a={l:!0,h:!0,o:!0});var c;a.h?a.W?c=new l({g:[b("eyes").s(0),b("eyes").s(1)],use:"eyes"}):c=b("eyes"):c=l.a;return new q({mouth:a.o?b("mouth"):
l.a,ears:a.l?b("ears"):l.a,eyes:c})};Q(A,y);A.prototype.C=function(){var a=this;this.f.querySelector(".unicomp-do-randomize").addEventListener("click",function(){return a.m()});for(var b={},c=z(this.f.querySelectorAll(".unicomp-edit .unicomp-edit-component")),e=c.next();!e.done;b={i:b.i,G:b.G,u:b.u},e=c.next()){b.u=e.value;b.G=b.u.querySelector("select");b.i=b.u.getAttribute("data-component");this.addEventListener("hover:"+b.i,function(f){return function(){a.f.querySelector(".unicomp-display .comp-"+
f.i).classList.add("active");a.f.querySelector('.unicomp-edit-component[data-component="'+f.i+'"]').classList.add("active")}}(b));this.addEventListener("unhover:"+b.i,function(f){return function(){a.f.querySelector(".unicomp-display .comp-"+f.i).classList.remove("active");a.f.querySelector('.unicomp-edit-component[data-component="'+f.i+'"]').classList.remove("active")}}(b));b.u.addEventListener("mouseover",function(f){return function(){return a.a(new Event("hover:"+f.i))}}(b));b.u.addEventListener("mouseout",
function(f){return function(){return a.a(new Event("unhover:"+f.i))}}(b));e=z(l.j[b.i]);for(var g=e.next();!g.done;g=e.next()){g=g.value;var h=document.createElement("option");h.textContent=g+"";h.innerHTML="&nbsp;"+h.innerHTML;h.value=JSON.stringify(g);b.G.appendChild(h)}b.u.querySelector("select").addEventListener("change",function(f){return function(){a.c.set(f.i,new l(JSON.parse(f.G.value)));a.a(new Event("change:creation"))}}(b));b.u.querySelector(".unicomp-edit-do-randomize").addEventListener("click",
function(f){return function(){a.c.set(f.i,l.b(f.i).M());a.a(new Event("change:creation"))}}(b));b.u.querySelector(".unicomp-enable").addEventListener("change",function(f){return function(){a.c.set(f.i,f.u.querySelector(".unicomp-enable").checked?new l(JSON.parse(f.G.value)):l.a);a.a(new Event("change:creation"))}}(b))}C(this.f.querySelectorAll(".unicomp-display"))};A.prototype.v=function(){var a=this,b=this.c;this.f.querySelector(".unicomp-display > .comp-ears.left").textContent=b.l.s(0);this.f.querySelector(".unicomp-display > .comp-eyes.left").textContent=
b.h.s(0);this.f.querySelector(".unicomp-display > .comp-mouth").textContent=b.o.s(0);this.f.querySelector(".unicomp-display > .comp-eyes.right").textContent=b.h.s(1);this.f.querySelector(".unicomp-display > .comp-ears.right").textContent=b.l.s(1);var c=this.f.querySelector(".unicomp-display");c.setAttribute("data-clipboard-text",b+"");for(var e={},g=z(this.f.querySelectorAll(".unicomp-edit .unicomp-edit-component")),h=g.next();!h.done;e={A:e.A},h=g.next()){var f=h.value;e.A=f.getAttribute("data-component");
h=JSON.stringify(b.get(e.A));c.querySelector(".comp-"+e.A).addEventListener("mouseover",function(v){return function(){a.a(new Event("hover:"+v.A))}}(e));c.querySelector(".comp-"+e.A).addEventListener("mouseout",function(v){return function(){a.a(new Event("unhover:"+v.A))}}(e));var m=!!b.get(e.A)&&!l.a.B(b.get(e.A));f.querySelector("select").disabled=!m;f.querySelector(".unicomp-edit-do-randomize").disabled=!m;if(f.querySelector(".unicomp-enable").checked=m)for(f=z(f.querySelectorAll("select option")),
m=f.next();!m.done;m=f.next())m=m.value,m.selected=m.value===h}};A.prototype.m=function(){this.b(q.random())};A.prototype.b=function(a){this.c=a;this.a(new Event("change:creation"))};Q(x,y);x.prototype.m=function(){var a=this,b=this.b();this.f.querySelector(".fav-when-empty").toggleAttribute("hidden",0!==b.length);var c=this.f.querySelector(".fav-container");for(c.toggleAttribute("hidden",0===b.length);c.hasChildNodes();)c.removeChild(c.lastChild);for(var e=document.querySelector("#unicomp-fav-template").innerHTML,
g={},h=z(b.entries()),f=h.next();!f.done;g={J:g.J,D:g.D},f=h.next()){f=z(f.value);g.J=f.next().value;g.D=f.next().value;f=document.createElement("div");f.innerHTML=e;f=f.firstElementChild;f.style.color="#"+g.D.N();f.querySelector(".text").appendChild(document.createTextNode(g.D+""));var m=f.querySelector(".content");m.setAttribute("data-clipboard-text",g.D+"");C([m]);f.querySelector(".do-edit").addEventListener("click",function(v){return function(t){t.stopPropagation();t=new Event("select");t.c=new q(b[v.J]);
a.a(t)}}(g));f.querySelector(".do-remove").addEventListener("click",function(v){return function(t){t.stopPropagation();b.splice(v.J,1);a.v(b);t=new Event("remove");t.c=v.D;a.a(t)}}(g));c.appendChild(f)}};x.prototype.b=function(){var a=window.localStorage.getItem("faces-favorites");return(a?JSON.parse(a):x.a).map(function(b){return new q(b)})};x.prototype.C=function(a){this.v([a].concat(this.b()));var b=new Event("add");b.c=a;this.a(b)};x.prototype.H=function(a){return this.b().some(function(b){return b.B(a)})};
x.prototype.v=function(a){a=JSON.stringify(a.map(function(b){return b.O()}));window.localStorage.setItem("faces-favorites",a);this.m();this.a(new Event("update"))};x.a="bW91dGh+dy5udy5pZV9leWVzfncubzEuNHdfZWFyc34xNC0xNQ== bW91dGh+Mm5fZXllc342eGMuN2ZrLTdma19lYXJzfjE0LTE1 bW91dGh+OW1zX2V5ZXN+X2VhcnN+NHYuMmsuMm4uMTQtMTUuMm4uMWIuNHY= bW91dGh+Mm5fZXllc34yaHNfZWFyc34= bW91dGh+NXI5X2V5ZXN+N2dwX2VhcnN+aXEtaXA= bW91dGh+NmRiX2V5ZXN+Mm1fZWFyc34= bW91dGh+dy5udy5pZV9leWVzfjdoMF9lYXJzfjE0LjlrNS0xNS45azU= bW91dGh+Mm5fZXllc35pZ19lYXJzfjg0Yy4xNC0xNS44M3o= bW91dGh+dy5udy5pZV9leWVzfncuMTljbS53X2VhcnN+N2oyLTdqMg== bW91dGh+dy5uei5pZV9leWVzfjRiNi00YjlfZWFyc34=".split(" ");
Q(w,y);w.prototype.b=function(a){var b=this.f.querySelector("#infinite-list-item-template").innerHTML;new DOMParser;var c=this.f.querySelector(".infinite-list");a=z(Array.a(a,function(){return q.random()}));for(var e=a.next();!e.done;e=a.next()){e=e.value;var g=e+"",h=document.createElement("div");h.innerHTML=b;h=h.firstElementChild;h.querySelector(".text").appendChild(document.createTextNode(g));h.style.color="#"+e.N();h.setAttribute("data-clipboard-text",g);C([h]);c.appendChild(h)}b=new Event("load");
b.total=c.querySelectorAll(".box-creation").length;this.a(b)};window.initInfinite=function(a){function b(f){f.f.querySelector(".infinite-list").insertAdjacentHTML("beforeend",'<div class="ad col-md-12">'+c.pop()+"</div>")}var c=[' '].reverse();l.v(a.face);var e=new w(document.querySelector(".faces-infinite"));b(e);var g=0;e.addEventListener("load",function(f){var m=Math.floor(Math.pow(f.total,1/3));g||(g=m);g!==m&&(window._paq.push(["setCustomVariable",2,"Infinities Scrolled",
f.total]),window._paq.push(["trackPageView",document.querySelector("title").innerText]),6<m&&0===m%2&&c.length&&b(e));g=m});a=z(["scroll","mousewheel","DOMMouseScroll"]);for(var h=a.next();!h.done;h=a.next())window.addEventListener(h.value,function(){document.body.clientHeight-window.scrollY<=window.innerHeight+50&&e.b(12)})};window.initApp=function(a){function b(){var r=m.H(g.c);document.querySelector(".unicomp-do-fav-add").disabled=r}var c=this;l.v(a.face);var e=document.querySelector("title").textContent.match(/^(.+)\s\|.+$/)[1],
g=new A(document.querySelector(".unicomp-creator")),h=new d(document.querySelector("#user-created")),f=new p([new k]),m=new x(document.querySelector(".unicomp-fav")),v=0,t=!0;g.addEventListener("change:creation",function(){var r=g.c,H=e+" | "+r;document.querySelector("title").textContent=H;f.m(r);b();var I=r.O();history.state!==I&&(history[t?"replaceState":"pushState"](I,H,window.location.pathname+"?cr="+encodeURIComponent(I)),t=!1);h.H(r);document.querySelector(".unicomp-do-copy").setAttribute("data-clipboard-text",
r+"");v++;window._paq.push(["setCustomVariable",1,"Faces Viewed",v]);(1<v&&5>v||0===v%5)&&window._paq.push(["trackPageView",H])});C(document.querySelectorAll(".unicomp-do-copy"));window.onpopstate=function(r){r.state&&g.b(new q(r.state))};document.querySelector(".unicomp-do-back").addEventListener("click",function(){history.back();window.scrollTo(0,0);setTimeout(function(){return window.scrollTo(0,0)},0)});f.addEventListener("share",function(r){window._paq.push(["trackEvent","Share",r.U+" / "+r.c])});
m.addEventListener("select",function(r){g.b(r.c)});m.addEventListener("add",function(r){b();window._paq.push(["trackEvent","Favorite Add",m.b().length+" / "+r.c])});m.addEventListener("remove",function(r){b();window._paq.push(["trackEvent","Favorite Rem",m.b().length+" / "+r.c])});h.addEventListener("select",function(r){g.b(r.c)});document.querySelector(".unicomp-do-fav-add").addEventListener("click",function(){m.C(g.c)});document.querySelector(".poss-combis").textContent=l.C();for(var O=z(document.querySelectorAll(".text-face")),
B=O.next();!B.done;B=O.next())B=B.value,B.setAttribute("title","Click to use"),B.addEventListener("click",function(){g.b(new q(c.getAttribute("data-face")))});if(a.S)try{g.b(new q(a.S))}catch(r){console.warn("Initial face was not encoded correctly. (\u00b4\u2022 _ \u2022`)"),g.m()}else g.b(new q("bW91dGh+dy5udy5pZV9leWVzfncubzEuNHdfZWFyc34xNC0xNQ=="))};Q(p,y);p.prototype.m=function(a){this.c=a;this.update()};p.prototype.update=function(){for(var a=z(this.b),b=a.next();!b.done;b=a.next()){b=b.value;
try{b.update(this.c)}catch(c){console.error(c)}}};Q(n,y);n.prototype.load=function(){this.a(new Event("load"))};Q(k,n);k.prototype.load=function(){var a=this;window.twttr?window.twttr.ready(function(){a.loaded=!0;a.a(new Event("load"))}):setTimeout(function(){return a.load()},10)};k.prototype.update=function(a){for(var b=z(this.b),c=b.next();!c.done;c=b.next())c=c.value,c.setAttribute("href","https://twitter.com/intent/tweet?url="+encodeURIComponent(window.URLROOT)+"&text="+encodeURIComponent(a+"")),
this.loaded&&window.twttr.widgets.load(c)};Q(d,y);d.prototype.T=function(a){var b=this.f.querySelector(".user-others-online-count");b.innerHTML="";b.appendChild(document.createTextNode(0<a?a:""))};d.prototype.H=function(a){fetch("/user/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({c:a.toJSON()})}).catch(function(b){console.error(b)})};d.prototype.C=function(a,b){this.m[Array.prototype.indexOf.call(b.parentNode.children,b)]=a;var c=b.querySelector(".text").cloneNode();
c.appendChild(document.createTextNode(a+""));b.querySelector(".content").setAttribute("data-clipboard-text",a+"");var e=b.querySelector(".content > .text");e.parentNode.insertBefore(c,e.nextSibling);b.classList.add("fadetext");b.style.color="#"+a.N();setTimeout(function(){var g=b.querySelector(".text");g.parentNode.removeChild(g);b.classList.remove("fadetext")},500)}})();
